### PR TITLE
refactor(e2e): remove protractor from client

### PR DESCRIPTION
**Pull request by RubenVermeulen**
Completes #806

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Oh, and when you squash them, you can put

```
Closes #806
```

In the commit message body so the issue gets close automatically, once this PR is merged.

**Comment by d3lm** [comment]
This LGTM. Well done 👏

**Comment by RubenVermeulen** [comment]
@PascalPrecht , thx for the review. I haven't squashed commits inside a PR before. You have some docs on that?

**Comment by PascalPrecht** [comment]
@RubenVermeulen unfortunately we don't. In your particular case there's two different ways to go about it:

1. Reset your last commit and simply add your last commit's changes to your second last commit (HEAD~1), then force push your branch.

2. Interactively rebase your last two commits and squash the last one into the second last one, then force push your branch.

Both will have the same result.

Option 1) would be:

```
$ git reset HEAD~1
$ git add .
$ git commit --amend
```

^ This puts HEAD on your previous commit but keeps the changes from your last commit, adds those to the index and then amends the last commit with those changes.

Option 2) would be:

```
$ git rebase -i HEAD~2
```

This opens an editor with a list of all commits from HEAD~2 upwards. Commits you wanna keep are set to "pick". All you have to do is to change the "pick" of the last commit to "s" or "squash". Close the editor, and you're good to go. This will then squash HEAD into HEAD~1.

Let me know if you need more help. We're available at https://gitter.im/machinelabs/machinelabs

**Comment by PascalPrecht** [comment]
Awesome! Great work @RubenVermeulen

**Pull request merged**
