### PR TITLE
fix(core): resolving problems as reported in #827

### LINKED ISSUE #827: Bug: When running npm run format:fix it fails
When I run `npm run format:fix` I get the following error. 
```
$ npm run format:fix

> @machinelabs/client@0.30.2 format:fix machinelabs\client
> npm run format:base -- --write


> @machinelabs/client@0.30.2 format:base machinelabs\client
> npm run prettier -- '{src,e2e}/**/*{.ts,.js,.json,.css,.scss}' "--write"


> @machinelabs/client@0.30.2 prettier machinelabs\client
> prettier --config ../.prettierrc --ignore-path ../.prettierignore "'{src,e2e}/**/*{.ts,.js,.json,.css,.scss}'" "--write"

[error] No matching files. Patterns tried: '{src,e2e}/**/*{.ts,.js,.json,.css,.scss}' !**/node_modules/** !./node_modules/**
npm ERR! code ELIFECYCLE
```

This is already discussed via gitter with @PascalPrecht. His initial thoughts: 

> I fear this has to do with the globbing patterns. They are prolly not supported on windows as they use \ instead of /

#### Please execute the following commands in your terminal and post the output here
OS: Windows
Node: v9.11.1
Yarn: 1.6.0

### PR DESCRIPTION
**Pull request by Jefiozie**
This will resolve the issue I had with my Windows OS. 
@SamVerschueren  is going to check it on his machine to verify this won't break other OS's.

Closes #827

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Awesome @Jefiozie ! Thank you for fixing this and thanks to @SamVerschueren for supporting here!

I think this can actually be merged as @Jefiozie verified on his machine, but I'm happy to wait for @SamVerschueren to verify as well.

You rock <3

**Comment by PascalPrecht** [comment]
And on that note, this LGTM

**Comment by PascalPrecht** [comment]
Actually, good point @SamVerschueren . This needs to be fixed in other packages as well. E.g. `server` has the same npm script.

@Jefiozie would you mind updating your PR to have this change applied to all packages inside `/machinelabs` ?

**Comment by Jefiozie** [comment]
@PascalPrecht no problem

**Comment by Jefiozie** [comment]
I think I got them all can double check if this is the case? Thanks

**Comment by PascalPrecht** [comment]
@Jefiozie This LGTM, can you sqash your commits and make one `fix()` commit out of it to address #827 please ?

Once travis is green, we can merge this then.

**Pull request merged**
