### PR TITLE
uiux(client): open guides & examples in new tab

### PR DESCRIPTION
**Pull request by faisalmuhammad**
Updates the "Guides & Examples" link to open in a new tab so that the user doesn't have to go back and forth in the browser.

### CODE REVIEW

**Comment by PascalPrecht** [comment]
While I'm personally in favor to decide myself as a user when I want to open in a new tab, I agree that this might be a good UX in this case. The changes look good to me @faisalmuhammad !

Can you do me a favor and update your commit message to match our commit message conventions?

Something like: `uiux(client): open guides & examples in new tab` should do the trick.

Let me know if you need help with this. Happy to merge this, once done! :)

**Comment by faisalmuhammad** [comment]
I have updated the commit message. Does editing here alone will update the commit message of do I have to execute any other commands? 

I agree that opening a link in new tab is users' personal preference. However, in this case ideally the user should not leave the editor page. For example, I have split screens and usually to view guides, I open them on one screen and have the editor opened in the other. I believe this is the case with most users.

**Comment by faisalmuhammad** [comment]
Hi @PascalPrecht , 

Running **`git commit --amend`** gives me this: 

Image of Yaktocat

Please note that I made the changes online on github, not on my local machine.

**Comment by PascalPrecht** [comment]
Yes exactly. What you see is the Vim editor which opens when you make changes to a commit message (you can configure Git to use any other editor, Vim is just the default).

As mentioned in the other comment, once you've changed the commit message, you need to force push into your PR branch again (`patch-1`) this will update the PR automatically.

Come over to https://gitter.im/machinelabs/machinelabs if you need help

**Pull request merged**
